### ISSUE TITLE
e2e: test for issue 5211 gets stuck

### ISSUE THREAD

**Issue by dtrudg** [sylabs/singularity#1109]
**Version of Singularity**

main

**Describe the bug**

Tests are timing out, relatively often, with the following symptom:

```
goroutine 47 [semacquire, 26 minutes]:
sync.runtime_Semacquire(0xc00059c808?)
	runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0xc00059c800)
	sync/waitgroup.go:139 +0xa6
github.com/sylabs/singularity/e2e/internal/e2e.TestEnv.RunSingularity({{0xc000501ce0, 0x1a}, {0xc000501e60, 0x1d}, {0xc000510990, 0x2a}, {0xc000164cc0, 0x14}, {0x1193e32, 0xe}, ...}, ...)
	github.com/sylabs/singularity/e2e/internal/e2e/singularitycmd.go:686 +0x573
github.com/sylabs/singularity/e2e/actions.actionTests.issue5211({{{0xc000501ce0, 0x1a}, {0xc000501e60, 0x1d}, {0xc000510990, 0x2a}, {0xc000164cc0, 0x14}, {0x1193e32, 0xe}, ...}}, ...)
	github.com/sylabs/singularity/e2e/actions/regressions.go:355 +0x533
github.com/sylabs/singularity/e2e/internal/testhelper.(*Suite).Run.func1.1.1(0x0?)
	github.com/sylabs/singularity/e2e/internal/testhelper/testhelper.go:96 +0x45
testing.tRunner(0xc00057c340, 0xc000124580)
	testing/testing.go:1446 +0x217
created by testing.(*T).Run
	testing/testing.go:1493 +0x75e
```

The execution of Singularity in actions / issue5211 is not exiting, and remains stuck.

**Comment by dtrudg** [comment]
Now seen at:

```
RUN   TestE2E/PAR/ACTIONS/action_basic_profiles/Fakeroot/ExecPidNsTrue
    actions.go:913: Running command "/usr/local/bin/singularity exec --fakeroot --pid /tmp/stest.807595737/test.sif true"
```

The tests tha hang are always `--fakeroot` execs, so far.

**Comment by dtrudg** [comment]
The issue occurs where the fakeroot cleanup runs `rm` via the fakeroot engine to remove the temporary container directory.

It can be reproduced with this script:

```
while :
do
    singularity exec --fakeroot  alpine_latest.sif /bin/true &
    singularity exec --fakeroot  alpine_latest.sif /bin/true &
    singularity exec --fakeroot  alpine_latest.sif /bin/true &
    singularity exec --fakeroot  alpine_latest.sif /bin/true &
    singularity exec --fakeroot  alpine_latest.sif /bin/true &
    singularity exec --fakeroot  alpine_latest.sif /bin/true &
    singularity exec --fakeroot  alpine_latest.sif /bin/true &
    singularity exec --fakeroot  alpine_latest.sif /bin/true &
    wait
done
```

On the Ubuntu 20.04 CircleCI environment, this script will hang within a few iterations.

On a RHEL8 VM with 4 cores, the script generally hangs for me within 100 iterations.

By adding additional logging, it is possible to localize the hang to the fakeroot MonitorContainer function:

https://github.com/sylabs/singularity/blob/1b6d557989b2cd9b9a6692cd81138a8c965c6f92/internal/pkg/runtime/engine/fakeroot/engine_linux.go#L258

In the signal monitoring loop, the function will `wait4` for the container pid, once it has received a `SIGCHLD`. However, in the cases where the fakeroot cleanup hangs, no `SIGCHLD` is ever received, and so the loop runs forever.

`signal.Notify` is called ahead of the process start, and logging shows that SIGCHLD is not being lost due to a filled channel buffer. It is not clear where the SIGCHLD that should reach the parent from the `rm` process is being lost. It seems somewhat dependent on load, and the kernel version. It has been much easier to observe this issue in highly parallel executions of Singularity, and the e2e-tests. It now manifests easily on Ubuntu 20.04 in the CircleCI environment, and also SLES EC2 instances. It reproduces on RHEL8 in a VM, but less easily. I cannot reproduce it at all on a Fedora 36 environment, even with higher load / parallelism.

As a workaround, the MonitorContainer process could be modified to perform a blocking wait for the container process in a go routine, seperate from signal handling... so that exit is not dependent on receiving the `SIGCHLD` reliably.
