### ISSUE TITLE
e2e: SLES12 panic when running e2e OCSP responder

### ISSUE THREAD

**Issue by dtrudg** [sylabs/singularity#1417]
**Version of Singularity**

3.11.0

**Describe the bug**

On SLES12 an unsupported key error prevents the e2e suite from starting the OCSP responder. There is a panic, so other tests don't run...

```
unable to load responder private key
    140357430437520:error:0609E09C:digital envelope routines:PKEY_SET_TYPE:unsupported algorithm:p_lib.c:239:
    140357430437520:error:0606F076:digital envelope routines:EVP_PKCS82PKEY:unsupported private key algorithm:evp_pkey.c:84:TYPE=1.3.101.112
    140357430437520:error:0907B00D:PEM routines:PEM_READ_BIO_PRIVATEKEY:ASN1 lib:pem_pkey.c:142:
    panic: responder initialization has failed due to 'exit status 1'
  
    goroutine 498 [running]:
    github.com/sylabs/singularity/e2e/verify.(*ctx).startOCSPResponder.func1()
            github.com/sylabs/singularity/e2e/verify/verify.go:248 +0x20a
    created by github.com/sylabs/singularity/e2e/verify.(*ctx).startOCSPResponder
            github.com/sylabs/singularity/e2e/verify/verify.go:238 +0xec
```

**Comment by dtrudg** [comment]
We should probably show a failure here, but ensure we don't panic.
