### ISSUE TITLE
No GPU automatically detected Error

### ISSUE THREAD

**Issue by williamty** [sylabs/singularity#776]
after run the following command in vagrant:
`$ singularity exec --nv ./container.simg bash -c "python main.py"`

I got an error:
```
INFO:    Could not find any NVIDIA binaries on this host!
WARNING: Could not find any NVIDIA libraries on this host!
WARNING: You may need to edit /usr/local/etc/singularity/nvliblist.conf
No GPU automatically detected. Setting SETTINGS.GPU to 0, and SETTINGS.NJOBS to cpu_count.
```
But I do have GPU. So what should I do next?

**Comment by dtrudg** [comment]
Hello, we need some more information here.

What version of Singularity is this (`singularity --version`) and how did you install it.

What version of the nvidia driver, CUDA packages etc. are installed on your system, and how did you install them? What Linux distribution are you using?

The error messages show that Singularity cannot find the NVIDIA libraries or binaries, so they are either not in the standard paths, or have not been installed.

**Comment by williamty** [comment]
Thank you for fast reply! But I returned to the WSL2 to figure out the problem........sorry
I tried after these steps: https://sylabs.io/2022/03/wsl2-gpu/

But I got another error:
```
$ singularity exec --nv --nvccli  --containall -B /home/xxx/GraN-DAG:/code/ ./
container.simg bash -c "cd /code && python main.py"
WARNING: When using nvidia-container-cli with --contain NVIDIA_VISIBLE_DEVICES must be set or no GPUs will be available in container.
INFO:    Setting --writable-tmpfs (required by nvidia-container-cli)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/cdt/utils/Settings.py", line 152, in autoset_settings
    devices = ast.literal_eval(os.environ["CUDA_VISIBLE_DEVICES"])
  File "/code/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'CUDA_VISIBLE_DEVICES'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 25, in <module>
    from gran_dag.main import main
  File "/code/gran_dag/main.py", line 23, in <module>
    import cdt
  File "/usr/local/lib/python3.7/dist-packages/cdt/__init__.py", line 28, in <module>
    import cdt.causality
  File "/usr/local/lib/python3.7/dist-packages/cdt/causality/__init__.py", line 24, in <module>
    from .pairwise import __init__
  File "/usr/local/lib/python3.7/dist-packages/cdt/causality/pairwise/__init__.py", line 24, in <module>
    from .ANM import ANM
  File "/usr/local/lib/python3.7/dist-packages/cdt/causality/pairwise/ANM.py", line 31, in <module>
    from .model import PairwiseModel
  File "/usr/local/lib/python3.7/dist-packages/cdt/causality/pairwise/model.py", line 31, in <module>
    from ...utils.Settings import SETTINGS
  File "/usr/local/lib/python3.7/dist-packages/cdt/utils/__init__.py", line 34, in <module>
    from .loss import (TTestCriterion,
  File "/usr/local/lib/python3.7/dist-packages/cdt/utils/loss.py", line 25, in <module>
    from .Settings import SETTINGS
  File "/usr/local/lib/python3.7/dist-packages/cdt/utils/Settings.py", line 176, in <module>
    SETTINGS = ConfigSettings()
  File "/usr/local/lib/python3.7/dist-packages/cdt/utils/Settings.py", line 92, in __init__
    self = autoset_settings(self)
  File "/usr/local/lib/python3.7/dist-packages/cdt/utils/Settings.py", line 163, in autoset_settings
    includeNan=False))
  File "/usr/local/lib/python3.7/dist-packages/GPUtil-1.4.0-py3.7.egg/GPUtil/GPUtil.py", line 140, in getAvailable
  File "/usr/local/lib/python3.7/dist-packages/GPUtil-1.4.0-py3.7.egg/GPUtil/GPUtil.py", line 102, in getGPUs
ValueError: invalid literal for int() with base 10: "NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running."
```

should I update the NVIDIA driver?

**Comment by williamty** [comment]
Got it. Thank you! btw, you're so diligent, always online, reply so soon.... salute!
